### ISSUE TITLE
Release 1.8.0

### ISSUE THREAD

**Issue by jordanmccullough** [github/training-kit#290]
Tracking issue for Training-Kit release 1.7.x:

~~- [ ] Intermediate curriculum updates **TBD**~~
~~- [ ] Advanced curriculum updates **TBD**~~
~~- [ ] *Longer* lived branch examples, slide topics https://github.com/github/training-kit/issues/247~~
- [x] Chapter abstracts/summaries
  - [x] Foundations slide deck https://github.com/github/training-kit/issues/258, https://github.com/github/training-kit/pull/292
  - [x] Intermediate slide deck https://github.com/github/training-kit/pull/298
  - [x] Advanced slide deck https://github.com/github/training-kit/pull/299
  - Style improvements in https://github.com/github/training-kit/pull/288 should permit better appearance for this feature
- [x] Objective list "checkboxes" in slide deck for each class https://github.com/github/training-kit/pull/303
- [x] Subversion Migration cheat sheet https://github.com/github/training-kit/issues/283
- [x] Cheat sheets web page as print layout
  - [x] Git Cheat Sheet https://github.com/github/training-kit/pull/295
  - [x] Subversion to Git https://github.com/github/training-kit/pull/293
- [x] Fix "teacher" mode and slide-only mode toggle bugs https://github.com/github/training-kit/pull/300
- [x] White space corrections https://github.com/github/training-kit/issues/297

**Comment by jordanmccullough** [comment]
1.8 shipped. https://github.com/github/training-kit/releases/tag/1.8.0
