### ISSUE TITLE
Open Source Community Updates

### ISSUE THREAD

**Issue by hollenberry** [github/training-kit#415]
With the recent move of our On Demand courses to Open Source, I think we have a great opportunity to fine tune some of the edges of our training-kit in a beginner-friendly way. 

## Proposed Next Steps With Examples
- [x] Update contributing.md with greater [detail] (https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md) @crichID **this is happening in #571**
  - [x] In open sourcing these materials, are you open to people contributing changes to the core material itself, or is this more about giving them permission to customize and reuse it themselves? Either way, it'd be good to clarify.
- [x] Update issue/PR templates for [beginners](https://github.com/hoodiehq/camp/issues/95) @hollenberry
- [x] Add labels based on [proficiency](http://up-for-grabs.net/#/), ability (technical writing, design, etc.) ( @brianamarie ) 
- [x] Make a more welcoming [README](https://github.com/exercism/exercism.io). @crichID
  - [x] Add image
  - [x] Add badge
  - [x] Add motivational messages.
  - [x] Include instructions for building On Demand
- [x] Include Style Guide ( @hectorsector and @beardofedu ) **this is happening in #436**
  - [ ] Update SEO
- [x] Slack/Gitter Channel
- ~~Create Maintainer's Guide~~ [To be moved internally]
- [x] Document the project's design, architecture, and directory structure (Mostly done in the README.md already, but can possibly be enhanced slightly)
- [x] Create a Code of Conduct **happening in #440**

Once we have a general agreement on the above steps, I'll break each of the above next steps out into separate issue threads with anticipated deadlines.

Please feel free to comment if anything else under this bucket should be added or if any of the above should be adjusted! I'm hoping to 🚢 quickly, before we promote that we've moved these courses to Open Source.

cc: @github/services-training , @kytrinyx

**Comment by brianamarie** [comment]
@kytrinyx & @lee-dohm, your involvement in open source communities is impressive and a source of inspiration! What do you think of this plan of action? What could we add?

@hollenberry Are you mostly wanting a review of this plan? Is it OK if we raise our hands to help out on the smaller items? I’d love to help with labels.

**Comment by hollenberry** [comment]
@brianamarie Are you mostly wanting a review of this plan? Is it OK if we raise our hands to help out on the smaller items? I’d love to help with labels.

Yes! I'm hoping that we can agree on the pieces, and then break them out into smaller items, but it's absolutely okay if you'd like to jump on some pieces earlier.

**Comment by beardofedu** [comment]
@hollenberry If I could suggest that we create a set of instructions / template (and formatting) description for the On Demand classes that might be helpful. 

As an example:
 - Text a student is going to type should be in a `code block`
 - Buttons a student is going to click should be **bold**. 
   - Also, we click buttons, we don't press them. We aren't ironing 👔s over here ;).

**Comment by hectorsector** [comment]
> If I could suggest that we create a set of instructions / template (and formatting) description for the On Demand classes that might be helpful.

@beardofedu I've thought about this before, also. But I think it needs to be bigger than that -- I like to think of it as a "style guide" for training artifacts. I'm happy to ✋ for this and open a separate PR with a first 🔪 .

**Comment by hollenberry** [comment]
Hey @brianamarie @hectorsector @beardofedu ! 

Thank you all so much for giving this a once over and adding your ideas. I was going to make issues for all of these, but I realized it probably makes more sense for you to open a PR/Issue etc. as you see fit for the items that you're going to tackle.

I'll open an Issue for the remaining pieces, but I want to remove any roadblocks in case you're looking to Open Source Friday 😄

**Comment by kytrinyx** [comment]
This sounds like a good plan! I generally feel like I have no idea what I'm doing when it comes to documentation and helping people get started, so I'll follow along and see if I learn anything!

**Comment by brianamarie** [comment]
Starting brainstorming on labels [in this issue](https://github.com/github/training-kit/issues/420).

**Comment by crichID** [comment]
@hollenberry thank you for organizing these thoughts! I put my name next to the README and CONTRIBUTING since it seems like they go together (kinda). PR forthcoming!

**Comment by brianamarie** [comment]
@hollenberry Another idea could be incorporating help for contributors into the gitter help for those going through the activities. [Check out Free Code Camp's 'contributor' room.](https://gitter.im/FreeCodeCamp/Contributors)

**Comment by hollenberry** [comment]
I'm about to tackle some first drafts for Issue/PR templates today. Saw [this](https://github.com/formly-js/angular-formly/issues/410#issuecomment-127227984) during the morning.

This might be 2.0, or only rolled out for a few labels, but I think it would be nice for us to have additional prompts depending on the type of label we apply. 
- Technical writing gets a reference to our style guide
- First-timers-only gets a comprehensive walkthrough of how to contribute, etc.

**Comment by hollenberry** [comment]
> Another idea could be incorporating help for contributors into the gitter help for those going through the activities. Check out Free Code Camp's 'contributor' room.

@brianamarie what a great idea! What do you think about having a Slack channel? 

This would allow us to maintain consistent conversations and establish break-out rooms depending on the project (open enrollment, training kit, languages, etc.)

I'm happy to PRP this today if I wouldn't be stepping on your toes!

**Comment by hectorsector** [comment]
> First-timers-only gets a comprehensive walkthrough of how to contribute, etc.

I think the comprehensive walkthrough is good, as well as the first-timers-only 👍, but I'd like to lower the barrier of entry for anyone and not impose a restriction that we'll only accept PRs from first-timers.

**Comment by hollenberry** [comment]
> I think the comprehensive walkthrough is good, as well as the first-timers-only 👍, but I'd like to lower the barrier of entry for anyone and not impose a restriction that we'll only accept PRs from first-timers.

@hectorsector 
I definitely understand where you're coming from. I'll reply to you and @beardofedu over in the label thread.

**Comment by hollenberry** [comment]
`bkeepers` posted [this](https://gitmagic.io/) in the open source channel today. Thoughts on adding it to the task list? 

I think it's a great idea during the beta period (no cost), and then we can evaluate the effectiveness. This also goes back to our conversations about people being more responsive to automated feedback.

**Comment by kytrinyx** [comment]
> I'd like to lower the barrier of entry for anyone and not impose a restriction that we'll only accept PRs from first-timers.

I've had this exact discussion with the other maintainers on Exercism. We've settled for "good first patch", which is suggestive of being excellent for first timers, without restricting it.

One maintainer currently keeps a stock of about 10 "good first patch" issues on his repo. If there are more than 10 he starts picking them off himself, and if there are fewer, he works on making more of them.

**Comment by brianamarie** [comment]
> I'm happy to PRP this today if I wouldn't be stepping on your toes!

Go for it @hollenberry, please feel free to assume that I wear steel toe boots at all times. 👢

**Comment by lee-dohm** [comment]
Thanks for the kind words @brianamarie :blush: Sorry it has taken so long for me to respond.  I think the plan you have so far is spot-on 👍 Some suggestions:

* In the CONTRIBUTING guide, explain your label system and include search links - [for example](https://github.com/github/training-kit/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)
* For an example of some of the things that might be useful in a style guide, you can check out the [Atom Flight Manual CONTRIBUTING guide](https://github.com/atom/flight-manual.atom.io/blob/master/CONTRIBUTING.md#conventions)
* Personally, I would recommend a Slack team over a Gitter channel if for no other reason than there are now a number of people at GitHub that are moderating Slack teams that you can turn to for questions 

With regard to Issue and PR templates, we have found that for text that is intended to guide the person posting the Issue or PR but isn't helpful after the Issue or PR is posted, using HTML comments `<!-- text here -->`  is best. A simplistic example:

```markdown
## Description

<!-- Enter the description of your issue here -->

## Steps to Reproduce

<!--
Use short, imperative sentences to describe step-by-step what you do to reproduce the problem. An example of a good repro step is "Open a file by selecting the File > Open menu"

At the end, include what you expected to happen and what actually happened so we can be sure we're understanding what you see.
-->
```

This way the person posting the item gets as much help as they need but people reading these items don't have to mentally filter out boilerplate text.

Let me know if I can clarify anything or give more assistance!

**Comment by brianamarie** [comment]
Issue/PR Labels have been updated. @github/services-training Is there any other item that anyone needs help on? It looks like everything above has a PRP, but if there's anything I could/should be looking at to help, ping me!

**Comment by hollenberry** [comment]
> Is there any other item that anyone needs help on? It looks like everything above has a PRP, but if there's anything I could/should be looking at to help, ping me!

Hey there @brianamarie ! Following up on the discussion in the templates thread, it looks like a maintainers guide might be a really helpful asset! I've added it above (PRPless).

**Comment by hectorsector** [comment]
The style guide has been started in #436

**Comment by brianamarie** [comment]
I also want to ping @Shubheksha for any ideas. @github/services-training, @Shubheksha is a Campus Expert as well as a real life expert. She has created a lot of materials for [promoting and maintaining healthy open source projects](https://medium.freecodecamp.com/how-to-attract-new-contributors-to-your-open-source-project-46f8b791d787#.v7pl8anij) and is also active in the Free Code Camp space. 

@Shubheksha we are hoping to not only improve this repository as an open source repository, but also think about what a free course on open source would look like. Are you interested in helping with something like that?

**Comment by hollenberry** [comment]
@brianamarie That resource is awesome! I'm adding two new items to the OP that we're missing from the list.

**Comment by crichID** [comment]
@github/services-training all of the tasks in the OP are either ✔️  or in progress in #436, #440 or #571. Given this, I am going to close out this issue :tada:

**Comment by Erik818subo** [comment]
Yep
